# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-13 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20170113_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_local_file',
            field=models.BooleanField(default=False),
        ),
    ]
