# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-15 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20170113_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default='a.no', upload_to=''),
        ),
    ]
